/* ═══════════════════════════════════════════════════════════════
   vocabulary.js — Rocket Typing word bank + sentence templates
   Restored to the categorized structure: nouns, verbs, adjectives,
   adverbs, prepositions, articles, months, days, years, ages — each
   kept as its own separate array (not merged), plus the templates
   object that fills them into grammatical sentence patterns like
   "{article} {adjective} {noun} {verb} {adverb}".

   This file is loaded (see index.html) before the main script runs,
   so 'vocabulary' and 'templates' are guaranteed to exist the
   moment generateSentence() first needs them.
   ═══════════════════════════════════════════════════════════════ */
        const vocabulary = {
nouns: ["ability", "absence", "academy", "account", "achievement", "acid", "action", "actor", "actress", "addition",
                "address", "advice", "affair", "age", "agency", "agent", "agreement", "air", "airport", "alarm",
                "album", "alcohol", "alert", "alien", "alliance", "alphabet", "ambition", "ambulance", "amount", "analysis",
                "analyst", "ancestor", "angel", "anger", "angle", "animal", "anniversary", "answer", "ant", "anxiety",
                "apartment", "apology", "apple", "application", "appointment", "approval", "area", "argument", "arm", "army",
                "arrival", "art", "article", "artist", "aspect", "assignment", "assistant", "association", "assumption", "atmosphere",
                "attack", "attempt", "attention", "attitude", "audience", "author", "authority", "average", "award", "baby",
                "background", "bacteria", "bag", "balance", "ball", "banana", "band", "bank", "bar", "base",
                "basket", "bath", "battery", "battle", "beach", "bear", "beauty", "bed", "bedroom", "beer",
                "beginning", "behavior", "belief", "bell", "belt", "bench", "benefit", "bird", "birth", "birthday",
                "biscuit", "bit", "blade", "blood", "board", "boat", "body", "bonus", "book", "boot",
                "border", "boss", "bottle", "bottom", "box", "boy", "brain", "branch", "bread", "breakfast",
                "breath", "bridge", "brother", "budget", "building", "bulb", "bus", "business", "butter", "button",
                "buyer", "cabin", "cabinet", "cable", "cake", "calendar", "camera", "camp", "campaign", "cancer",
                "candidate", "candle", "candy", "capital", "car", "card", "care", "career", "carpet", "case",
                "cash", "cat", "category", "cause", "ceiling", "celebration", "cell", "center", "century", "ceremony",
                "chair", "challenge", "champion", "chance", "change", "channel", "chapter", "character", "charge", "charity",
                "chart", "check", "cheese", "chef", "child", "choice", "church", "circle", "city", "class",
                "classroom", "client", "climate", "clock", "closet", "cloud", "club", "coach", "coast", "coat",
                "coffee", "coin", "collection", "college", "color", "combination", "comfort", "committee", "communication", "community",
                "company", "comparison", "competition", "complaint", "computer", "concept", "concern", "concert", "conclusion", "condition",
                "conference", "confidence", "conflict", "connection", "consequence", "construction", "contact", "content", "contest", "context",
                "contract", "control", "conversation", "cookie", "corner", "cost", "country", "courage", "course", "court",
                "cousin", "craft", "credit", "crime", "criticism", "crowd", "culture", "cup", "currency", "customer",
                "cycle", "dad", "damage", "dance", "danger", "data", "date", "daughter", "day", "dealer",
                "death", "debate", "debt", "decision", "definition", "degree", "delivery", "demand", "department", "departure",
                "depth", "description", "design", "desire", "desk", "detail", "development", "device", "dialogue", "diamond",
                "difference", "difficulty", "dinner", "direction", "director", "disease", "disk", "display", "distance", "district",
                "doctor", "document", "dog", "door", "dream", "dress", "drink", "driver", "drop", "drug",
                "earth", "economy", "edge", "editor", "education", "effect", "effort", "egg", "election", "element",
                "elevator", "emotion", "emphasis", "employee", "employer", "energy", "engine", "engineer", "environment", "episode",
                "equipment", "error", "estate", "event", "evidence", "example", "exchange", "excitement", "exercise", "experience",
                "experiment", "expert", "explanation", "expression", "eye", "face", "fact", "factor", "failure", "family",
                "fan", "farm", "farmer", "father", "fear", "feature", "feedback", "festival", "field", "figure",
                "film", "finger", "fire", "fish", "flight", "flower", "focus", "food", "football", "force",
                "forest", "form", "fortune", "foundation", "friend", "fruit", "fuel", "function", "funeral", "future",
                "game", "garden", "gas", "gate", "gene", "gift", "girl", "glass", "goal", "government",
                "grade", "grandfather", "grandmother", "grass", "ground", "group", "growth", "guest", "guide", "guitar",
                "hair", "half", "hall", "hand", "happiness", "hat", "head", "health", "heart", "heat",
                "height", "hero", "history", "holiday", "home", "honey", "hope", "hospital", "hotel", "hour",
                "house", "human", "humor", "idea", "image", "impact", "importance", "impression", "improvement", "incident",
                "income", "industry", "insect", "inspection", "inspiration", "instance", "instruction", "insurance", "intention", "interaction",
                "interest", "internet", "interview", "investment", "issue", "item", "job", "journal", "journey", "judge",
                "juice", "key", "kid", "king", "kitchen", "knowledge", "lab", "ladder", "lake", "lamp",
                "land", "language", "law", "leader", "leaf", "learning", "lecture", "leg", "lesson", "letter",
                "level", "library", "life", "light", "limit", "line", "lion", "list", "location", "love",
                "machine", "magazine", "mail", "manager", "map", "market", "marriage", "material", "meal", "meaning",
                "measurement", "meat", "media", "medicine", "member", "memory", "message", "metal", "method", "middle",
                "milk", "mind", "minute", "mirror", "mission", "mistake", "model", "moment", "money", "month",
                "morning", "mother", "motor", "mountain", "mouse", "mouth", "movie", "music", "name", "nation",
                "nature", "neck", "need", "neighbor", "network", "news", "night", "noise", "note", "number",
                "object", "obligation", "observation", "occasion", "office", "officer", "oil", "operation", "opinion", "opportunity",
                "option", "order", "organization", "origin", "outcome", "oven", "owner", "oxygen", "package", "page",
                "pain", "painting", "paper", "parent", "park", "part", "partner", "party", "passenger", "passion",
                "patient", "pattern", "payment", "peace", "pen", "pencil", "people", "performance", "period", "permission",
                "person", "personality", "phone", "photo", "phrase", "physics", "piano", "picture", "piece", "pilot",
                "pizza", "place", "plan", "plane", "planet", "plant", "player", "poem", "poet", "point",
                "police", "policy", "politics", "pollution", "population", "position", "possibility", "power", "practice", "presence",
                "president", "pressure", "price", "problem", "process", "product", "profession", "professor", "program", "project",
                "promise", "property", "proposal", "protection", "protein", "protest", "purpose", "quality", "quantity", "queen",
                "question", "radio", "rain", "range", "rate", "reaction", "reader", "reality", "reason", "recipe",
                "recognition", "record", "reflection", "region", "relationship", "religion", "reputation", "request", "research", "resource",
                "response", "restaurant", "result", "revenue", "review", "river", "road", "role", "room", "rule",
                "runner", "safety", "sale", "salt", "sample", "sand", "satisfaction", "school", "science", "screen",
                "sea", "season", "secret", "section", "security", "selection", "self", "sense", "series", "service",
                "session", "shadow", "shape", "share", "sheep", "sheet", "ship", "shirt", "shock", "shoe",
                "shop", "shot", "shoulder", "signal", "signature", "significance", "silence", "silver", "sister", "skill",
                "skin", "sky", "sleep", "smile", "snow", "society", "software", "soil", "solution", "son",
                "song", "sound", "source", "space", "speaker", "speech", "speed", "spirit", "sport", "spot",
                "spring", "square", "stage", "star", "statement", "station", "status", "step", "stock", "stone",
                "story", "strategy", "street", "strength", "student", "studio", "study", "style", "subject", "success",
                "sugar", "suggestion", "summer", "sun", "support", "surface", "surgery", "surprise", "survey", "system",
                "table", "talent", "task", "tax", "teacher", "team", "technology", "temperature", "term", "test",
                "text", " theory", "thing", "thought", "ticket", "time", "title", "tool", "tooth", "topic",
                "town", "trade", "tradition", "traffic", "train", "trainer", "transport", "travel", "tree", "trend",
                "trial", "trip", "trust", "truth", "uncle", "unit", "university", "user", "value", "variation",
                "vehicle", "version", "video", "view", "village", "violence", "vision", "visit", "voice", "volume",
                "waiter", "walk", "wall", "war", "warning", "water", "wealth", "weather", "website", "week",
                "weight", "wife", "wind", "window", "winner", "winter", "woman", "wood", "word", "work",
                "worker", "world", "writer", "year", "youth", "zone"],
            verbs: ["accept", "achieve", "acknowledge", "adapt", "add", "adjust", "admire", "admit", "adopt", "advise",
                "afford", "agree", "aim", "allow", "announce", "anticipate", "apologize", "appear", "apply", "appoint",
                "appreciate", "approve", "argue", "arrange", "arrest", "arrive", "ask", "assume", "assure", "attach",
                "attempt", "attend", "attract", "avoid", "awake", "balance", "ban", "bathe", "be", "bear", "beat",
                "become", "begin", "behave", "believe", "belong", "bend", "bet", "bind", "bite", "blame", "bless",
                "blink", "blow", "boast", "boil", "borrow", "bounce", "break", "breathe", "bring", "broadcast", "build",
                "burn", "burst", "buy", "calculate", "call", "capture", "care", "carry", "catch", "cause", "celebrate",
                "change", "charge", "chase", "cheat", "check", "cheer", "choose", "circle", "claim", "clean", "clear",
                "climb", "close", "coach", "collect", "color", "comb", "combine", "come", "commit", "communicate", "compare",
                "compete", "complain", "complete", "concentrate", "concern", "conclude", "confirm", "connect", "consider", "consist",
                "contain", "continue", "control", "convert", "cook", "copy", "correct", "cost", "count", "cover", "create",
                "cross", "cry", "cut", "damage", "dance", "deal", "decide", "declare", "decorate", "decrease", "define",
                "delay", "deliver", "demand", "deny", "depend", "describe", "deserve", "design", "destroy", "detect", "develop",
                "die", "disagree", "discover", "discuss", "dismiss", "display", "divide", "do", "draw", "dream", "drink",
                "drive", "drop", "earn", "eat", "educate", "emphasize", "enable", "encourage", "end", "enjoy", "enter",
                "establish", "estimate", "evaluate", "examine", "exist", "expect", "explain", "express", "extend", "face",
                "fail", "fall", "fancy", "fasten", "favor", "fear", "feed", "feel", "fight", "fill", "find",
                "finish", "fit", "fix", "fold", "follow", "force", "forget", "forgive", "form", "found", "gain",
                "gather", "get", "give", "glance", "go", "grab", "grow", "guess", "handle", "hang", "happen",
                "hate", "have", "hear", "help", "hide", "highlight", "hit", "hold", "hope", "hug", "hunt",
                "identify", "ignore", "imagine", "impress", "improve", "include", "increase", "influence", "inform", "insist",
                "intend", "introduce", "invest", "invite", "involve", "iron", "judge", "jump", "keep", "kick", "kill",
                "kiss", "know", "label", "laugh", "lay", "lead", "learn", "leave", "lend", "let", "like",
                "listen", "live", "load", "lock", "look", "lose", "love", "maintain", "manage", "mark", "marry",
                "match", "matter", "measure", "meet", "mention", "mind", "miss", "mix", "move", "multiply", "need",
                "note", "notice", "obey", "observe", "obtain", "occur", "offer", "open", "operate", "order", "organize",
                "originate", "own", "pack", "paint", "participate", "pass", "pause", "pay", "perform", "permit", "persuade",
                "pick", "place", "plan", "play", "point", "pose", "post", "practice", "prefer", "prepare", "press",
                "pretend", "prevent", "print", "produce", "protect", "prove", "provide", "publish", "pull", "punch", "purchase",
                "push", "qualify", "question", "quit", "race", "raise", "reach", "read", "realize", "receive", "recognize",
                "recommend", "record", "reduce", "refer", "reflect", "refuse", "regret", "relate", "release", "rely", "remain",
                "remember", "remind", "remove", "repair", "repeat", "replace", "reply", "report", "represent", "request", "require",
                "rescue", "reserve", "resist", "respond", "rest", "result", "return", "reveal", "rise", "run", "rush",
                "sacrifice", "satisfy", "save", "say", "scan", "schedule", "search", "see", "seek", "seem", "select",
                "sell", "send", "serve", "set", "settle", "share", "shout", "show", "shut", "sign", "signal",
                "sing", "sit", "sleep", "slide", "slip", "smile", "solve", "sort", "sound", "speak", "specify",
                "spend", "spill", "spin", "split", "spread", "stand", "start", "stay", "steal", "stick", "stir",
                "stop", "study", "succeed", "suffer", "suggest", "sum", "support", "suppose", "surprise", "surround", "take",
                "talk", "teach", "tell", "tempt", "test", "thank", "think", "throw", "touch", "train", "transfer",
                "translate", "travel", "treat", "try", "turn", "understand", "undo", "unite", "use", "utilize", "validate",
                "value", "visit", "wait", "wake", "walk", "want", "warn", "wash", "watch", "wave", "wear", "weigh",
                "win", "wish", "withdraw", "wonder", "work", "worry", "wrap", "write", "yell", "zoom",
                "accelerate", "acknowledge", "act", "administer", "advertise", "alleviate", "amuse", "analyze", "announce", "anticipate",
                "applaud", "apprehend", "approximate", "argue", "arouse", "assemble", "assess", "astonish", "attach", "attain",
                "attribute", "authorize", "balance", "bargain", "beam", "belch", "benefit", "blush", "bolster", "broadcast",
                "bruise", "calculate", "calm", "capitalize", "cater", "certify", "challenge", "change", "charge", "charm",
                "clarify", "classify", "cooperate", "coordinate", "correlate", "counter", "criticize", "decrease", "defend", "define",
                "deliver", "demonstrate", "depend", "deplore", "derive", "describe", "design", "determine", "devise", "differentiate",
                "disclose", "discover", "display", "distribute", "diversify", "dominate", "elaborate", "elect", "eliminate", "emerge",
                "encircle", "enforce", "enhance", "enrich", "ensue", "entail", "entertain", "establish", "evaluate", "exceed",
                "excite", "execute", "exercise", "exhibit", "expand", "expedite", "explore", "express", "facilitate", "falsify",
                "fascinate", "finance", "formulate", "fulfill", "generate", "guide", "harmonize", "illustrate", "implement", "impose",
                "improve", "incorporate", "increase", "influence", "inform", "initiate", "innovate", "inspect", "inspire", "integrate",
                "intensify", "interact", "intercede", "interfere", "intervene", "introduce", "investigate", "invoke", "involve", "justify",
                "lecture", "legislate", "liquidate", "maintain", "manipulate", "mediate", "monitor", "motivate", "negotiate", "observe",
                "obstruct", "occupy", "operate", "oppose", "optimize", "organize", "originate", "overcome", "oversee", "participate",
                "perceive", "perform", "persuade", "plan", "practice", "predict", "prepare", "prescribe", "present", "press",
                "prevent", "prioritize", "proceed", "process", "produce", "program", "progress", "project", "promote", "propose",
                "protect", "prove", "provide", "publicize", "pursue", "qualify", "quantify", "question", "raise", "realize",
                "reassure", "rebuild", "receive", "recognize", "recommend", "reconcile", "record", "recover", "recruit", "refer",
                "reflect", "reform", "regulate", "reinforce", "relate", "release", "relieve", "rely", "remain", "remind",
                "remove", "render", "repair", "repeat", "replace", "report", "represent", "request", "require", "research",
                "resolve", "respond", "restore", "restrict", "result", "retain", "reveal", "revise", "review", "revitalize",
                "reward", "run", "safeguard", "satisfy", "save", "schedule", "scrutinize", "search", "secure", "select",
                "sell", "send", "separate", "serve", "set", "settle", "share", "simplify", "simulate", "solve",
                "sort", "specify", "stimulate", "strategize", "strengthen", "structure", "study", "substantiate", "submit", "substitute",
                "succeed", "suggest", "summarize", "supervise", "support", "supplement", "supply", "surpass", "sustain", "symbolize",
                "systematize", "teach", "terminate", "test", "track", "train", "translate", "transmit", "treat", "trigger",
                "unify", "update", "upgrade", "use", "utilize", "validate", "value", "verify", "visualize", "win"],
            adjectives: ["able", "abundant", "acceptable", "accurate", "active", "adaptable", "adorable", "adventurous", "afraid", "aggressive",
                "alert", "alive", "amazing", "ambitious", "ample", "ancient", "angry", "annoying", "anxious", "apprehensive",
                "appropriate", "arrogant", "artistic", "ashamed", "assured", "astonishing", "attractive", "average", "awesome", "awful",
                "bad", "beautiful", "better", "best", "bewildered", "big", "bizarre", "bitter", "black", "blue",
                "blushing", "boiling", "bored", "boring", "brainy", "brave", "breakable", "bright", "brilliant", "broken",
                "bruised", "bubbly", "bulky", "busy", "calm", "careful", "careless", "caring", "cautious", "charming",
                "cheap", "cheerful", "chief", "chilly", "chubby", "clean", "clear", "clever", "clumsy", "cold",
                "colorful", "comfortable", "common", "complicated", "confident", "confused", "conscious", "considerate", "constant", "content",
                "convincing", "cool", "cooperative", "courageous", "crazy", "creamy", "creative", "crooked", "cruel", "curious",
                "cute", "dangerous", "daring", "dark", "dead", "defeated", "defiant", "delicious", "delightful", "dependent",
                "descriptive", "deserted", "detailed", "determined", "different", "difficult", "digital", "diligent", "dim", "diminutive",
                "direct", "dirty", "disgusted", "distinct", "disturbed", "dizzy", "double", "drab", "dry", "dull",
                "dutiful", "eager", "early", "earnest", "easy", "economic", "educational", "effective", "efficient", "elated",
                "elderly", "electric", "elegant", "embarrassed", "emotional", "empty", "enchanting", "encouraging", "energetic", "enormous",
                "entire", "envious", "equal", "essential", "esteemed", "ethical", "euphoric", "even", "excellent", "excited",
                "exciting", "exotic", "expensive", "extra", "extreme", "faint", "fair", "faithful", "famous", "fancy",
                "fantastic", "far", "fast", "fatal", "favorite", "fearful", "fearless", "feisty", "fellow", "female",
                "fertile", "festive", "few", "fierce", "fine", "financial", "first", "fit", "flaky", "flat",
                "flawless", "flickering", "fluffy", "fluttering", "fond", "foolish", "foreign", "foremost", "formal", "fortunate",
                "fragile", "frail", "frantic", "free", "fresh", "friendly", "frightened", "fun", "funny", "furry",
                "futile", "future", "fuzzy", "generous", "gentle", "giant", "giddy", "gigantic", "glamorous", "gleaming",
                "glistening", "glorious", "good", "gorgeous", "graceful", "gracious", "grand", "gray", "great", "greedy",
                "green", "growing", "grumpy", "guarded", "handsome", "happy", "hard", "harmful", "harsh", "hasty",
                "healthy", "helpful", "helpless", "hidden", "high", "hilarious", "historical", "honest", "honorable", "hopeful",
                "horrible", "hostile", "hot", "huge", "humble", "humorous", "hungry", "hurried", "hurtful", "husky",
                "ideal", "identical", "idiotic", "ignorant", "ill", "illegal", "illustrious", "imaginary", "imaginative", "immense",
                "impartial", "important", "impossible", "incredible", "independent", "innocent", "inquisitive", "insane", "insecure", "intelligent",
                "interesting", "internal", "international", "intrepid", "intrigued", "intriguing", "irate", "itchy", "jaded", "jagged",
                "jealous", "jittery", "jolly", "joyful", "joyous", "jubilant", "judicious", "juicy", "junior", "kaput",
                "keen", "kind", "kindhearted", "knowledgeable", "large", "last", "late", "lazy", "lean", "left",
                "legal", "light", "likeable", "likely", "lively", "lonely", "long", "longing", "loose", "loud",
                "lovable", "lovely", "loving", "low", "loyal", "lucky", "luminous", "mad", "magical", "magnificent",
                "main", "major", "male", "married", "massive", "material", "mature", "mean", "measly", "medical",
                "melodic", "mellow", "memorable", "merry", "messy", "metallic", "mighty", "military", "mini", "minor",
                "misleading", "modern", "modest", "moist", "monstrous", "moral", "motionless", "mountainous", "muddy", "musical",
                "mute", "mysterious", "naive", "narrow", "nasty", "natural", "naughty", "near", "neat", "necessary",
                "needy", "negative", "neighboring", "nervous", "new", "nice", "nifty", "nimble", "noisy", "normal",
                "notable", "noted", "novel", "numerous", "nutritious", "obese", "obedient", "obnoxious", "odd", "offensive",
                "old", "old-fashioned", "open", "optimal", "optimistic", "ordinary", "organic", "original", "outgoing", "outstanding",
                "overconfident", "overjoyed", "overlooked", "panicky", "parallel", "parched", "partial", "passionate", "past", "peaceful",
                "perfect", "periodic", "perky", "persistent", "personal", "petty", "philosophical", "physical", "pink", "plain",
                "playful", "pleasant", "plump", "polished", "polite", "poor", "popular", "positive", "powerful", "precious",
                "present", "pretty", "previous", "pricey", "prickly", "pristine", "private", "proud", "psychological", "public",
                "puny", "pure", "purple", "puzzled", "puzzling", "quaint", "qualified", "quarrelsome", "quick", "quiet",
                "quirky", "quizzical", "radiant", "ragged", "rainy", "rapid", "rare", "raw", "ready", "real",
                "reasonable", "recent", "reckless", "rectangular", "red", "reflective", "regular", "relaxed", "reliable", "relieved",
                "remarkable", "remote", "repentant", "responsible", "restless", "rich", "rigid", "right", "ripe", "roasted",
                "robust", "romantic", "roomy", "rough", "round", "royal", "ruddy", "rude", "runny", "sad",
                "sadistic", "safe", "salty", "satisfying", "scary", "scientific", "second", "secret", "selfish", "sensitive",
                "serene", "serious", "severe", "shabby", "shadowy", "shallow", "sharp", "shiny", "shocked", "short",
                "short-term", "showy", "shrill", "shy", "sick", "silent", "silky", "silly", "simple", "simplistic",
                "sinful", "single", "sizable", "skilled", "skinny", "sleepy", "slight", "slim", "slimy", "slippery",
                "slow", "small", "smart", "smelly", "smooth", "snappy", "snarling", "sneaky", "snug", "social",
                "sociable", "soft", "soggy", "solid", "somber", "sophisticated", "sore", "sour", "Spanish", "sparkling",
                "sparse", "specific", "spectacular", "speedy", "spicy", "spirited", "spiteful", "splendid", "spotless", "square",
                "squeaky", "stable", "stale", "standard", "starchy", "steady", "steep", "sticky", "stiff", "stimulating",
                "stingy", "stormy", "straight", "strange", "strong", "studious", "stunning", "substantial", "successful", "succulent",
                "sudden", "sufficient", "super", "superb", "superficial", "superior", "supportive", "surprising", "suspicious", "sweet",
                "sweltering", "swift", "sympathetic", "tall", "tame", "tan", "tangible", "tart", "tasty", "tattered",
                "teeny", "temporary", "tender", "tense", "terrible", "thankful", "thick", "thin", "third", "thirsty",
                "thorough", "thoughtful", "thoughtless", "tidy", "tight", "tiny", "tired", "tough", "troubled", "true",
                "trusting", "trustworthy", "truthful", "turbulent", "ugly", "ultimate", "unacceptable", "unaware", "uncomfortable", "uncommon",
                "unconscious", "understood", "unequal", "uneven", "unfortunate", "unhappy", "unhealthy", "uniform", "unique", "united",
                "unkempt", "unknown", "unlawful", "unlucky", "unnecessary", "unpleasant", "unrealistic", "unselfish", "unsightly", "untidy",
                "unused", "unusual", "unwelcome", "unwilling", "upbeat", "upright", "upset", "urban", "useful", "useless",
                "usual", "utter", "vacant", "vague", "valuable", "variable", "vast", "vegetarian", "vengeful", "versatile",
                "vibrant", "victorious", "vicious", "violent", "vivacious", "vital", "voracious", "vulnerable", "warm", "wary",
                "weak", "wealthy", "weary", "well", "wet", "whimsical", "white", "whole", "wicked", "wide",
                "wild", "willing", "windy", "wise", "witty", "wonderful", "worried", "worthless", "worthy", "wrong",
                "yellow", "young", "youthful", "zealous"],
            adverbs: ["abruptly", "accidentally", "accordingly", "accurately", "actively", "adversely", "afterward", "almost", "always", "angrily",
                "anxiously", "appreciably", "arrogantly", "awkwardly", "badly", "barely", "beautifully", "boldly", "bravely", "briefly",
                "brightly", "briskly", "busily", "calmly", "carefully", "carelessly", "cautiously", "certainly", "cheerfully", "closely",
                "coherently", "comfortably", "commonly", "completely", "constantly", "correctly", "courageously", "crossly", "cruelly", "curiously",
                "daily", "daintily", "daringly", "dearly", "deceptively", "deeply", "defiantly", "deliberately", "delightfully", "densely",
                "desperately", "determinedly", "differently", "directly", "distinctly", "doubtfully", "dramatically", "eagerly", "early", "easily",
                "economically", "effectively", "efficiently", "elaborately", "elegantly", "elsewhere", "emotionally", "enormously", "enthusiastically", "equally",
                "especially", "essentially", "even", "eventually", "exactly", "exceedingly", "exceptionally", "excitedly", "exclusively", "extensively",
                "externally", "extremely", "fairly", "faithfully", "famously", "far", "fast", "fatally", "favorably", "ferociously",
                "fervently", "finally", "firmly", "flatly", "fluently", "fondly", "foolishly", "fortunately", "frankly", "frequently",
                "freshly", "fully", "furiously", "generally", "generously", "gently", "gladly", "gracefully", "gradually", "gratefully",
                "greatly", "greedily", "happily", "hard", "hardly", "harshly", "hastily", "healthily", "heavily", "helpfully",
                "honestly", "hopelessly", "hourly", "hungrily", "hurriedly", "immediately", "importantly", "incessantly", "indeed", "independently",
                "indifferently", "indirectly", "innocently", "insufficiently", "intensely", "intentionally", "intermittently", "internally", "intimately", "invariably",
                "ironically", "jovially", "joyfully", "judgmentally", "justly", "keenly", "kindly", "lazily", "lightly", "likely",
                "literally", "lively", "logically", "loosely", "loudly", "lovingly", "loyally", "madly", "mainly", "manually",
                "marvelously", "meanly", "mechanically", "mentally", "merrily", "meticulously", "mightily", "miserably", "moderately", "monthly",
                "more", "moreover", "mostly", "naturally", "nearly", "necessarily", "neatly", "nervously", "never", "nicely",
                "noisily", "normally", "notably", "not", "obediently", "objectively", "obviously", "occasionally", "oddly", "offensively",
                "often", "only", "openly", "optimistically", "ordinarily", "outdoors", "outwardly", "painfully", "partially", "particularly",
                "passionately", "patiently", "perfectly", "persistently", "physically", "plainly", "playfully", "politely", "poorly", "positively",
                "possibly", "potentially", "powerfully", "promptly", "properly", "quickly", "quietly", "rapidly", "rarely", "readily",
                "really", "reasonably", "recently", "recklessly", "regularly", "relatively", "reliably", "reluctantly", "remarkably", "remotely",
                "repeatedly", "resolutely", "respectfully", "restlessly", "rigidly", "roughly", "rudely", "sadly", "safely", "scarcely",
                "secretly", "seemingly", "selfishly", "sensibly", "seriously", "sharply", "sheepishly", "shortly", "shrilly", "shyly",
                "sincerely", "sleepily", "slowly", "smoothly", "softly", "solemnly", "solidly", "somewhat", "soon", "specifically",
                "specially", "speedily", "stealthily", "sternly", "strictly", "strongly", "successfully", "suddenly", "superbly", "supposedly",
                "surely", "surprisingly", "suspiciously", "sweetly", "swiftly", "sympathetically", "systematically", "tactfully", "tensely", "terribly",
                "thankfully", "thoroughly", "thoughtfully", "tightly", "together", "tomorrow", "too", "totally", "tranquilly", "truly",
                "ultimately", "unabashedly", "unavoidably", "uncertainly", "understandably", "undoubtedly", "unexpectedly", "unfortunately", "universally", "upstairs",
                "upward", "urgently", "usually", "utterly", "vacantly", "vaguely", "valiantly", "vastly", "verbally", "very",
                "violently", "visibly", "voluntarily", "warmly", "weakly", "wearily", "well", "wetly", "wholly", "wildly",
                "wisely", "wonderfully", "wrongly", "yearly", "yesterday", "youthfully", "zealously", "abundantly", "accusingly", "actively",
                "adoringly", "adventurously", "affectionately", "amazingly", "angrily", "anxiously", "approvingly", "assertively", "astonishingly", "audibly",
                "awkwardly", "beautifully", "bitterly", "blissfully", "boldly", "briskly", "brutally", "busily", "calmly", "carefully",
                "cautiously", "cheerfully", "clearly", "closely", "coherently", "comfortably", "commonly", "completely", "confidently", "consciously",
                "consistently", "constantly", "coolly", "courageously", "crossly", "cruelly", "curiously", "daily", "daringly", "dearly",
                "deceptively", "deeply", "defiantly", "deliberately", "delightfully", "densely", "desperately", "determinedly", "differently", "directly",
                "distinctly", "doubtfully", "dramatically", "eagerly", "earnestly", "easily", "effectively", "efficiently", "elegantly", "emotionally",
                "enormously", "enthusiastically", "equally", "especially", "essentially", "even", "eventually", "exactly", "exceedingly", "exceptionally",
                "excitedly", "exclusively", "extensively", "externally", "extremely", "fairly", "faithfully", "famously", "far", "fast",
                "favorably", "ferociously", "fervently", "finally", "firmly", "fluently", "fondly", "fortunately", "frankly", "frequently",
                "fully", "furiously", "generally", "generously", "gently", "gladly", "gracefully", "gradually", "gratefully", "greatly",
                "happily", "hard", "hardly", "harshly", "hastily", "healthily", "heavily", "helpfully", "honestly", "hopelessly",
                "hourly", "hungrily", "hurriedly", "immediately", "importantly", "incessantly", "indeed", "independently", "indifferently", "indirectly",
                "innocently", "intensely", "intentionally", "intermittently", "internally", "intimately", "invariably", "ironically", "jovially", "joyfully",
                "judgmentally", "justly", "keenly", "kindly", "lazily", "lightly", "likely", "literally", "lively", "logically",
                "loosely", "loudly", "lovingly", "loyally", "madly", "mainly", "manually", "marvelously", "meanly", "mentally",
                "merrily", "meticulously", "mightily", "miserably", "moderately", "monthly", "more", "moreover", "mostly", "naturally",
                "nearly", "necessarily", "neatly", "nervously", "never", "nicely", "noisily", "normally", "notably", "obediently",
                "objectively", "obviously", "occasionally", "oddly", "offensively", "often", "only", "openly", "optimistically", "ordinarily",
                "outdoors", "outwardly", "painfully", "partially", "particularly", "passionately", "patiently", "perfectly", "persistently", "physically",
                "plainly", "playfully", "politely", "poorly", "positively", "possibly", "potentially", "powerfully", "promptly", "properly",
                "quickly", "quietly", "rapidly", "rarely", "readily", "really", "reasonably", "recently", "recklessly", "regularly",
                "relatively", "reliably", "reluctantly", "remarkably", "remotely", "repeatedly", "resolutely", "respectfully", "restlessly", "rigidly",
                "roughly", "rudely", "sadly", "safely", "scarcely", "secretly", "seemingly", "selfishly", "sensibly", "seriously",
                "sharply", "sheepishly", "shortly", "shrilly", "shyly", "sincerely", "sleepily", "slowly", "smoothly", "softly",
                "solemnly", "solidly", "somewhat", "soon", "specifically", "speedily", "stealthily", "sternly", "strictly", "strongly",
                "successfully", "suddenly", "superbly", "supposedly", "surely", "surprisingly", "suspiciously", "sweetly", "swiftly", "sympathetically",
                "systematically", "tactfully", "tensely", "terribly", "thankfully", "thoroughly", "thoughtfully", "tightly", "together", "totally",
                "tranquilly", "truly", "ultimately", "unabashedly", "unavoidably", "uncertainly", "understandably", "undoubtedly", "unexpectedly", "unfortunately",
                "universally", "upstairs", "upward", "urgently", "usually", "utterly", "vacantly", "vaguely", "valiantly", "vastly",
                "verbally", "very", "violently", "visibly", "voluntarily", "warmly", "weakly", "wearily", "well", "wet",
                "wholly", "wildly", "wisely", "wonderfully", "wrongly", "yearly", "yesterday", "youthfully", "zealously"],
            prepositions: ["about", "above", "across", "after", "against", "along", "amid", "among", "around", "as",
                "at", "before", "behind", "below", "beneath", "beside", "besides", "between", "beyond", "but",
                "by", "concerning", "considering", "despite", "down", "during", "except", "following", "for", "from",
                "in", "inside", "into", "like", "minus", "near", "of", "off", "on", "onto",
                "opposite", "out", "outside", "over", "past", "per", "plus", "regarding", "round", "save",
                "since", "than", "through", "throughout", "till", "to", "toward", "towards", "under", "underneath",
                "unlike", "until", "up", "upon", "versus", "via", "with", "within", "without", "according to",
                "ahead of", "apart from", "as far as", "as of", "as per", "as well as", "aside from", "because of", "close to", "due to",
                "except for", "far from", "in addition to", "in case of", "in front of", "in lieu of", "in place of", "in spite of", "inside of", "instead of",
                "next to", "on account of", "on top of", "out of", "outside of", "owing to", "prior to", "pursuant to", "regardless of", "subsequent to",
                "such as", "thanks to", "up to", "with regard to", "with respect to", "by means of", "in accordance with", "in relation to", "in respect of", "on behalf of"],
            articles: ["a", "an", "the", "this", "that", "these", "those", "my", "your", "his", "her", "its", "our", "their",
                "all", "another", "any", "both", "each", "either", "enough", "few", "fewer", "fewest", "many", "more", "most",
                "much", "neither", "no", "other", "several", "some", "such", "what", "which", "whose", "each and every", "certain",
                "certainly", "half", "little", "less", "least", "plenty", "various", "one", "two", "three", "first", "second", "third"],
            months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
            days: Array.from({ length: 31 }, (_, i) => String(i + 1)),
            years: Array.from({ length: 124 }, (_, i) => String(1900 + i)),
            ages: Array.from({ length: 100 }, (_, i) => String(i + 1))
        };
        const templates = {
            easy: [
                "{article} {adjective} {noun} {verb} {adverb}",
                "{article} {noun} {verb} {preposition} {article} {adjective} {noun}",
                "{article} {adjective} {noun} {verb} the {noun}",
                "{article} {noun} {adverb} {verb} {preposition} the {noun}"
            ],
            medium: [
                "{article} {adjective} {noun} {verb} {adverb}.",
                "{article} {noun} {verb} {preposition} {article} {adjective} {noun}.",
                "{article} {adjective} {noun} {verb} the {noun}.",
                "{article} {noun} {adverb} {verb} {preposition} the {noun}."
            ],
            hard: [
                "{article} {adjective} {noun} {verb} {adverb} in {year}.",
                "{article} {noun} {verb} {preposition} {article} {adjective} {noun} on {month} {day}, {year}.",
                "The {adjective} {noun} is {age} years old.",
                "The {noun}'s date of birth is {month} {day}, {year}.",
                "The {noun} said, \"{adjective}!\""
            ]
        };